apiVersion: apps/v1
kind: Deployment
metadata:
  name: showview
  labels:
    app: showview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showview
  template:
    metadata:
      labels:
        app: showview
    spec:
      containers:
        - name: showview
          image: username/showview:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5